
package com.wz.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceImpl", targetNamespace = "http://service.wz.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<com.wz.service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://service.wz.com/", className = "com.wz.service.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://service.wz.com/", className = "com.wz.service.GetUsersResponse")
    @Action(input = "http://service.wz.com/UserServiceImpl/getUsersRequest", output = "http://service.wz.com/UserServiceImpl/getUsersResponse")
    public List<User> getUsers();

}
